let adminClient=null;
let activeResource='projects';
let resourceRows={};
const resources={
  projects:{title:'Projects',table:'projects',image:'image_url',fields:[['title','Project title','text',true],['slug','URL slug','text',true],['category','Category','text',true],['year','Year','text',true],['client_name','Client name','text',false],['services','Services','text',false],['excerpt','Short description','textarea',true],['description','Full project story','textarea',false],['image_url','Cover image URL','image',false],['sort_order','Display order','number',false],['featured','Featured project','checkbox',false],['published','Published','checkbox',false]]},
  services:{title:'Services',table:'services',fields:[['title','Service name','text',true],['icon','Icon or symbol','text',false],['description','Description','textarea',true],['sort_order','Display order','number',false],['published','Published','checkbox',false]]},
  clients:{title:'Clients & Logos',table:'clients',image:'logo_url',fields:[['name','Client name','text',true],['website_url','Website URL','url',false],['logo_url','Logo URL','image',false],['sort_order','Display order','number',false],['published','Published','checkbox',false]]},
  testimonials:{title:'Testimonials',table:'testimonials',fields:[['quote','Testimonial','textarea',true],['client_name','Client name','text',true],['client_role','Client type or role','text',false],['sort_order','Display order','number',false],['published','Published','checkbox',false]]},
  faqs:{title:'FAQs',table:'faqs',fields:[['question','Question','text',true],['answer','Answer','textarea',true],['sort_order','Display order','number',false],['published','Published','checkbox',false]]},
  stats:{title:'Statistics',table:'stats',fields:[['value','Value','text',true],['label','Label','text',true],['sort_order','Display order','number',false],['published','Published','checkbox',false]]}
};
const settingsFields=[['eyebrow','Hero eyebrow'],['hero_line_1','Hero line one'],['hero_line_2','Hero line two'],['hero_description','Hero description'],['intro_title','Intro title'],['intro_body','Intro paragraph'],['about_title','About title'],['about_body','About paragraph'],['email','Email address'],['phone','Phone'],['location','Location line'],['instagram','Instagram URL'],['linkedin','LinkedIn URL'],['behance','Behance URL'],['primary_cta_label','Primary button label'],['primary_cta_url','Primary button URL'],['secondary_cta_label','Secondary button label'],['secondary_cta_url','Secondary button URL'],['footer_blurb','Footer description']];

function ready(){const c=window.CREATIFY_CMS||{};return Boolean(c.supabaseUrl&&c.supabaseAnonKey&&window.supabase?.createClient)}
function db(){if(!ready())return null;adminClient ||= window.supabase.createClient(window.CREATIFY_CMS.supabaseUrl,window.CREATIFY_CMS.supabaseAnonKey);return adminClient}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function notice(msg,type='success'){const el=document.getElementById('adminNotice');el.textContent=msg;el.className=`admin-notice show ${type}`;clearTimeout(notice.t);notice.t=setTimeout(()=>el.classList.remove('show'),4500)}
function slugify(v=''){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}

async function initAdmin(){
  document.getElementById('configRequired').hidden=ready(); document.getElementById('authArea').hidden=!ready(); if(!ready())return;
  document.getElementById('loginForm').addEventListener('submit',login); document.getElementById('logoutButton').addEventListener('click',()=>db().auth.signOut());
  document.querySelectorAll('[data-admin-tab]').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.adminTab)));
  document.getElementById('addItem').addEventListener('click',()=>openEditor(activeResource)); document.getElementById('closeEditor').addEventListener('click',closeEditor); document.querySelector('.editor-backdrop').addEventListener('click',closeEditor);
  document.getElementById('resourceForm').addEventListener('submit',saveResource); document.getElementById('settingsForm').addEventListener('submit',saveSettings);
  const {data}=await db().auth.getSession(); setAuth(data.session); db().auth.onAuthStateChange((_e,s)=>setAuth(s));
}
async function login(e){e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await db().auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)notice(error.message,'error')}
function setAuth(session){document.getElementById('loginPanel').hidden=Boolean(session);document.getElementById('dashboard').hidden=!session;document.getElementById('loggedInEmail').textContent=session?.user?.email||'';if(session)loadDashboard()}
function showTab(name){document.querySelectorAll('[data-admin-tab]').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===name));document.querySelectorAll('[data-admin-panel]').forEach(p=>p.hidden=p.dataset.adminPanel!==name);if(resources[name]){activeResource=name;renderResourcePanel(name)}if(name==='settings')loadSettings();if(name==='inquiries')loadInquiries()}
async function loadDashboard(){await Promise.all([...Object.keys(resources).map(loadResource),loadSettings(),loadInquiries()]);renderResourcePanel('projects')}
async function loadResource(name){const r=resources[name];const {data,error}=await db().from(r.table).select('*').order('sort_order',{ascending:true});if(error)return notice(error.message,'error');resourceRows[name]=data||[]}
function renderResourcePanel(name){const r=resources[name],mount=document.getElementById('resourceList');document.getElementById('resourceTitle').textContent=r.title;document.getElementById('addItem').hidden=false;const rows=resourceRows[name]||[];mount.innerHTML=rows.length?rows.map(row=>{const title=row.title||row.name||row.question||row.client_name||row.label||'Item';const subtitle=row.category||row.client_role||row.description||row.answer||row.value||'';const img=r.image&&row[r.image]?`<img class="admin-thumb" src="${esc(row[r.image])}" alt="">`:`<div class="admin-thumb placeholder">${esc(title.slice(0,2).toUpperCase())}</div>`;return `<article class="admin-list-item">${img}<div><span class="badge ${row.published?'':'draft'}">${row.published?'Published':'Draft'}</span><h3>${esc(title)}</h3><p>${esc(String(subtitle).slice(0,100))}</p></div><div class="admin-actions"><button class="button secondary small" data-edit="${row.id}">Edit</button><button class="button small orange" data-delete="${row.id}">Delete</button></div></article>`}).join(''):'<p class="muted">No items yet.</p>';mount.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(name,b.dataset.edit));mount.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteResource(name,b.dataset.delete))}
function openEditor(name,id=''){activeResource=name;const r=resources[name],row=(resourceRows[name]||[]).find(x=>String(x.id)===String(id))||{};document.getElementById('editorTitle').textContent=`${id?'Edit':'Add'} ${r.title.replace(/s$/,'')}`;document.getElementById('resourceName').value=name;document.getElementById('resourceId').value=id;document.getElementById('editorFields').innerHTML=r.fields.map(([key,label,type,required])=>fieldHtml(key,label,type,row[key],required)).join('');const titleInput=document.querySelector('[name=title]'),slugInput=document.querySelector('[name=slug]');if(titleInput&&slugInput&&!id)titleInput.addEventListener('input',()=>slugInput.value=slugify(titleInput.value));document.getElementById('editorDrawer').classList.add('open')}
function fieldHtml(key,label,type,value,required){if(type==='checkbox')return `<label class="field checkbox-field"><input type="checkbox" name="${key}" ${value?'checked':''}><span>${label}</span></label>`;if(type==='textarea')return `<label class="field full"><span>${label}</span><textarea name="${key}" ${required?'required':''}>${esc(value||'')}</textarea></label>`;if(type==='image')return `<div class="field full"><label for="${key}">${label}</label><input id="${key}" name="${key}" value="${esc(value||'')}"><input type="file" name="${key}_file" accept="image/*"><small class="muted">Paste a URL or upload a file.</small></div>`;return `<label class="field ${key==='excerpt'||key==='description'?'full':''}"><span>${label}</span><input type="${type}" name="${key}" value="${esc(value??(type==='number'?0:''))}" ${required?'required':''}></label>`}
function closeEditor(){document.getElementById('editorDrawer').classList.remove('open');document.getElementById('resourceForm').reset()}
async function upload(file,folder){if(!file?.size)return'';const ext=file.name.split('.').pop().toLowerCase();const path=`${folder}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await db().storage.from(window.CREATIFY_CMS.storageBucket||'creatify-media').upload(path,file,{upsert:false});if(error)throw error;return db().storage.from(window.CREATIFY_CMS.storageBucket||'creatify-media').getPublicUrl(path).data.publicUrl}
async function saveResource(e){e.preventDefault();const form=e.currentTarget,fd=new FormData(form),name=fd.get('resourceName'),id=fd.get('resourceId'),r=resources[name],payload={};try{for(const [key,_label,type] of r.fields){if(type==='checkbox')payload[key]=form.elements[key].checked;else if(type==='number')payload[key]=Number(fd.get(key)||0);else if(type==='image'){let url=String(fd.get(key)||'').trim();const file=fd.get(`${key}_file`);if(file?.size)url=await upload(file,name);payload[key]=url}else payload[key]=String(fd.get(key)||'').trim()}let result=id?await db().from(r.table).update(payload).eq('id',id):await db().from(r.table).insert(payload);if(result.error)throw result.error;notice(`${r.title} updated.`);closeEditor();await loadResource(name);renderResourcePanel(name)}catch(err){notice(err.message,'error')}}
async function deleteResource(name,id){if(!confirm('Delete this item permanently?'))return;const {error}=await db().from(resources[name].table).delete().eq('id',id);if(error)return notice(error.message,'error');notice('Item deleted.');await loadResource(name);renderResourcePanel(name)}
async function loadSettings(){const form=document.getElementById('settingsForm');if(!form)return;const {data,error}=await db().from('site_settings').select('*').limit(1).maybeSingle();if(error)return notice(error.message,'error');document.getElementById('settingsFields').innerHTML=settingsFields.map(([key,label])=>`<label class="field ${['hero_description','intro_body','about_body','footer_blurb'].includes(key)?'full':''}"><span>${label}</span>${['hero_description','intro_body','about_body','footer_blurb'].includes(key)?`<textarea name="${key}">${esc(data?.[key]||'')}</textarea>`:`<input name="${key}" value="${esc(data?.[key]||'')}">`}</label>`).join('');document.getElementById('settingsId').value=data?.id||''}
async function saveSettings(e){e.preventDefault();const fd=new FormData(e.currentTarget),payload={};settingsFields.forEach(([key])=>payload[key]=String(fd.get(key)||'').trim());const id=fd.get('id');const {error}=id?await db().from('site_settings').update(payload).eq('id',id):await db().from('site_settings').insert(payload);if(error)return notice(error.message,'error');notice('Website settings updated live.');loadSettings()}
async function loadInquiries(){const mount=document.getElementById('inquiryList');if(!mount)return;const {data,error}=await db().from('inquiries').select('*').order('created_at',{ascending:false});if(error)return notice(error.message,'error');mount.innerHTML=data?.length?data.map(x=>`<article class="inquiry-card"><h3>${esc(x.name)} · ${esc(x.service||'General enquiry')}</h3><div class="inquiry-meta"><span>${esc(x.email)}</span><span>${esc(x.company||'No company')}</span><span>${new Date(x.created_at).toLocaleString()}</span></div><p>${esc(x.message)}</p><div class="admin-actions"><a class="button secondary small" href="mailto:${esc(x.email)}">Reply</a><button class="button small" data-read="${x.id}">${x.status==='read'?'Marked read':'Mark as read'}</button></div></article>`).join(''):'<p class="muted">No enquiries yet.</p>';mount.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await db().from('inquiries').update({status:'read'}).eq('id',b.dataset.read);loadInquiries()})}
document.addEventListener('DOMContentLoaded',initAdmin);
